backend:
  name: git-gateway
  branch: dev

media_folder: static/assets
public_folder: assets

collections:
  - name: about
    label: About Document
    folder: src/content/about
    create: true
    fields:
      - { name: type, widget: hidden, default: about }
      - { name: slug, label: Path, hint: Usually the url-escaped title }
      - { name: title, label: Title, widget: "string" }
      - { name: body, label: Body, widget: markdown }
  
  - name: challenges
    label: Challenge
    folder: src/content/challenges
    create: true
    fields:
      - { name: type, widget: hidden, default: challenge }
      - { name: date, label: Start Date, widget: datetime, timeFormat: false, dateFormat: true}
      - { name: title, label: Title, hint: "Not \"August 2019\""}
      - { name: desc, label: Description, hint: Displayed on the Challenges page, widget: text}
      - { name: repo, label: Repository, default: "https://github.com/developerhangout/MonthYear"}
      - { name: active, label: Active, hint: Display this challenge?, widget: boolean}
      - { name: body, label: Body, widget: markdown, hint: No H1 please!}
  
  - name: content-creators
    label: Content Creator
    folder: src/content/content-creators
    create: true
    fields:
      - { name: type, widget: hidden, default: content-creator }
      - { name: name, label: Real Name }
      - { name: username, label: Username }
      - { name: featuredImage, label: Image, widget: image, allow_multiple: false }
      - { name: socialLinks, label: Links, widget: list, hint: "Comma-separated list of links to youtube, website, etc." }
      - { name: body, label: Body, widget: markdown }
  
  - name: projects
    label: Project
    folder: src/content/projects
    create: true
    fields:
      - { name: type, widget: hidden, default: project }
      - { name: title, label: Title, widget: "string" }
      - { name: user, label: User, widget: string, hint: The user who submitted the project }
      - { name: date, label: Date Submitted, widget: datetime, timeFormat: false}
      - { name: tech, label: Tech Used, widget: list, hint: "Comma-separated list. Javascript, python, etc."}
      - name: links,
        label: Links,
        widget: object,
        fields:
          - { name: site, label: Website, widget: string }
          - { name: demo, label: Live Demo, widget: string }
          - { name: repo, label: Repository, widget: string }
      - { name: body, label: Body, widget: markdown }

  - name: resources
    label: Resource
    folder: src/content/resources
    create: true
    fields:
      - { name: type, widget: hidden, default: resource }
      - { name: title, label: Title, widget: "string" }
      - { name: url, label: URL, widget: "string" }
      - { name: user, label: User, widget: "string", hint: Username of whoever submitted the resource }
      - { name: featuredImage, label: Image, required: false, widget: "image", accept_multiple: false }
      - { name: body, label: Description, widget: markdown }
  
  - name: staff
    label: Staff
    folder: src/content/staff
    create: true
    fields:
      - { name: type, widget: hidden, default: staff }
      - { name: name, label: Real Name, widget: "string" }
      - { name: username, label: Username, widget: "string" }
      - { name: featuredImage, label: Image, widget: image, accept_multiple: false }
      - { name: body, label: Description, widget: markdown }