import React from "react"
import Layout from "../../components/layout"
import SEO from "../../components/seo";

const ProjectsPage = () => {
  return (
    <Layout>
      <SEO title="Projects" />
      <h1>TODO Add Stuff to go here</h1>
      <h2>List of projects generated by the community, make search able have someone who know react actually do that part</h2>
    </Layout>
  )
}

export default ProjectsPage
