import React from "react"
import Layout from "../../components/layout";
import SEO from "../../components/seo";
import { graphql, Link } from "gatsby";

const ChallengePage = ({ data }) => {
 const {allMarkdownRemark: challenge} = data;

  return(
    <Layout>
      <SEO title="Challenges" />
      <h1>TODO Add Stuff to go here</h1>
      <h2>Each challenge will have it's own page generated by markdown. this page is a landing page for all challenges such as "hey here are the past 10 challenges, etc"</h2>
      {challenge.edges.map(({node: post}) => {
        return <p key={post.id}>
          {post.frontmatter.title}
          {post.frontmatter.desc}
          <Link to={post.frontmatter.path}>go to challenge</Link>
        </p>
      })}
    </Layout>
     )
}

export default ChallengePage;

export const query = graphql`
query RecentChallenges {
  allMarkdownRemark(
    limit: 10
    sort: { fields: frontmatter___title, order: DESC }
  ) {
    edges {
      node {
        id
        frontmatter {
          title
          path
          desc
        }
      }
    }
  }
}
`
